# Generated by Django 3.2.4 on 2021-06-29 02:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('male_yield', models.IntegerField()),
                ('male_selectivity', models.IntegerField()),
                ('female_yield', models.IntegerField()),
                ('female_selectivity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Scores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('act_compostite25', models.IntegerField()),
                ('act_english25', models.IntegerField()),
                ('act_math25', models.IntegerField()),
                ('sat_compostite25', models.IntegerField()),
                ('sat_english25', models.IntegerField()),
                ('sat_math25', models.IntegerField()),
                ('act_composite75', models.IntegerField()),
                ('act_english75', models.IntegerField()),
                ('act_math75', models.IntegerField()),
                ('sat_composite75', models.IntegerField()),
                ('sat_english75', models.IntegerField()),
                ('sat_math75', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('ipeds', models.IntegerField()),
                ('AdmissionStats', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='college.admissionstats')),
                ('scores', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='college.scores')),
            ],
        ),
    ]
